#pragma once
//#define HOMEKIT_DEBUG
#define CJSON_USE_PREALLOCATED_BUFFER
#define TLV_USE_PREALLOCATED_BUFFER
#if defined(ARDUINO) && defined(ESP8266)
#define ARDUINO8266_SERVER

#define ARDUINO8266_SERVER_CPP

//#define HOMEKIT_DEBUG
#define HOMEKIT_SHORT_APPLE_UUIDS
#define HOMEKIT_OVERCLOCK_PAIR_SETUP
#endif 